### ISSUE TITLE
Stacer isn't correctly tracking network history?

### ISSUE THREAD

**Issue by SnuggIes** [oguzhaninan/Stacer#100]
For some reason, Stacer isn't correctly tracking my network history. Only using ethernet. OpenVPN installed but not connected. It appears to only spike when network starts being used. I can reproduce and feel free to ask for more information, if necessary. c:

Please see: [https://www.youtube.com/watch?v=1MWoyopk7wg](https://www.youtube.com/watch?v=1MWoyopk7wg)

**Stacer Version:** 1.07 (Reinstalled multiple times)
**OS:** Ubuntu 17.04 x86_64

**Comment by oguzhaninan** [comment]
Thank you for your attention.
I fixed this problem in the new version. I will publish soon.

**Comment by oguzhaninan** [comment]
You can try the [new version](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.8).  If the problem persists, please inform me.

**Comment by comradedakota** [comment]
I can confirm, I'm still having the same problem. I assume it's an issue similar to one I had with Conky a ways back... Config file is probably pointing to the incorrect network interface. Any idea where that setting is specified?
