### ISSUE TITLE
Stacer on kubuntu 17.04 does not work

### ISSUE THREAD

**Issue by tnilzon** [oguzhaninan/Stacer#75]
When trying to clean anything from within Satcer an error message is shown: "System Cleaning Failed" (text in a red colored field).

Stacer version: 1.0.7
Linux: kubuntu 17.04

/Tomas Nilzon

**Comment by oguzhaninan** [comment]
Hi,
If you have the "~/.config/Stacer/stacer.log" file please send me.

**Comment by tnilzon** [comment]
Sorry for the delay, but here is my logfile you asked for.
[stacer.zip](https://github.com/oguzhaninan/Stacer/files/1127049/stacer.zip)

**Comment by kayron8** [comment]
Hi @oguzhaninan,

I have the exactly problem than @tnilzon. Attached you can find stacer.log file
[stacer.zip](https://github.com/oguzhaninan/Stacer/files/1133689/stacer.zip)

Thank you very much for your attention and have a nice day!

**Comment by oguzhaninan** [comment]
@tnilzon 
The system cleaner is running smoothly. The problem of showing error is related to KDE. In the new version I will fix this error. Is there a problem other than the error message?

**Comment by oguzhaninan** [comment]
Hi @kayron8 ,
What exactly is your problem ?

**Comment by kayron8** [comment]
As shown by the following screenshot :)

![screenshot_20170715_170930](https://user-images.githubusercontent.com/29688238/28240377-3233a7ba-6981-11e7-8089-9fbf1b3e2ed9.png)

**Comment by tnilzon** [comment]
Is there a fix on the way for this error in Kubuntu?
Hope there is a new version released soon1
/Tomas Nilzon

**Comment by oguzhaninan** [comment]
I fixed the problem. You can try the [new version](https://github.com/oguzhaninan/Stacer/releases/tag/v1.0.8).

**Comment by tnilzon** [comment]
I have now tried the new version. The problem is still there, it behaves exactly the same way as the previous version.
 
Kubuntu 17.04 64bit
Stacer v 1.0.8

**Comment by oguzhaninan** [comment]
Hi, 
What exactly is the problem.

**Comment by tnilzon** [comment]
The problem is as described in previous message (look above):  'kayron8 commented on Jul 15 • edited'
See screen dump in that post.
The red flag with the text "System Cleaning Failed" pops up when trying cleaning/removing the files.

**Comment by oguzhaninan** [comment]
There is no error message in the new version. How did you decide it was an error?

**Comment by tnilzon** [comment]
Message shown is in the red box from the screen dump in post 'kayron8 commented on Jul 15 • edited' above.

![selection_001](https://user-images.githubusercontent.com/6920015/29717304-f08fbfb2-89ae-11e7-8666-7b6fe66e0b3d.jpg)

**Comment by oguzhaninan** [comment]
Do you have a problem with the new version. This is the old version.
Do you have a problem when you scan in the new version and clean up?

**Comment by tnilzon** [comment]
The problem is still on the new version. It behaves exactly as the old version.

**Comment by oguzhaninan** [comment]
Do you send a screenshot about the error for the new version.

**Comment by tnilzon** [comment]
The screenshot is from the old version. But the behaviour is exactly the same with the message "System Cleaning Failed" for the new version.

**Comment by oguzhaninan** [comment]
It's exactly what you mean by behavior. Did not delete a file you want to delete. Without the error message, how do you understand it is an error ?

**Comment by tnilzon** [comment]
If the message is "System Cleaning Failed", it must that the file(s) could not be removed. And the file(s) is selected to be cleaned is still there, no cleaning is done.

**Comment by oguzhaninan** [comment]
You are right, but there are no messages in the new version. The 1.0.7 version is incorrect.

**Comment by oguzhaninan** [comment]
If there is a problem with version 1.0.8, it is better to take a screenshot.

**Comment by tnilzon** [comment]
I am so awfully sorry. Just discovered I had version 1.0.7 still installed. Version 1.0.8 is OK.
Sorry for taking your time, my mistake.
:-(

**Comment by oguzhaninan** [comment]
It's okay, thank you.
